MercedesBlog/config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  resources :posts
  resources :image, only: [:create, :destroy]
end

MercedesBlog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MercedesBlog/app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
end

MercedesBlog/app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
end

MercedesBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
end

MercedesBlog/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def create
    @picture = Picture.new(image_params)
    @picture.save
    respond_to do |format|
      format.json { render :json => { url: @picture.image.url(:large), picture_id: @picture.id } }
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    picture.destroy
    respond_to do |format|
      format.json { render json: { status: :ok } }
    end
  end

  private

  def image_params
    params.require(:picture).permit(:image)
  end
end

MercedesBlog/app/controllers/posts_controller.rb
class PostsController<ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, success: 'Статья успешно создана'
    else
      flash.now[:danger] = 'Статья не создана'
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success: 'Succesfuly deleted'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :summary, :body, :image)
  end

end

MercedesBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

MercedesBlog/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

MercedesBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MercedesBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="card mt-1">
    <div class="container">
    <div class="nav">
      <a class="navbar-brand">
        <%= image_tag "/assets/mblogo.svg", height: '30', width: '30'%>
        Mercedes-Benz Blog
      </a>
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item ml-2 mr-2">
              <%= link_to 'All Article', posts_path, class:'btn btn-primary'%>
            </li>
            <li class="nav-item ml-2 mr-2">
              <%= link_to 'New Article', new_post_path, class:'btn btn-primary' %>
            </li>
        </ul>
    </div>
    </div>

    <div class="container mt-3 ьи-5">
    <%= yield %>
    </div>

  </div>

</html>

MercedesBlog/app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

    var disqus_config = function () {
    this.page.url = 'http://localhost.com<%= request.original_fullpath %>';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @post.id %>' // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://MercedesBlog.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>

MercedesBlog/app/views/posts/_form.html.erb
<%=form_for  @post, html: {multipert: true} do |f|%>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_field :summary, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.trix_editor :body , class: 'editor'%>
    </div>

  <div class="form-group">
    <%= f.submit 'Create', class:'btn btn-primary' %>
  </div>

<% end %>

MercedesBlog/app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head mt-2 mb-2">
    <h2 class="card-title"><%= link_to post.title, post_path(post) %></h2>
    <small> <%= post.created_at.to_date.strftime("%d %B, %Y")%></small>
    |
    <%= link_to 'Change', edit_post_path(post) %>
    <%= link_to 'Delete', post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %>
  </section>

  <section class="post-summary">

  </section>
</article>

MercedesBlog/app/views/posts/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

MercedesBlog/app/views/posts/index.html.erb
<h1>Posts</h1>

<%= render @posts %>

MercedesBlog/app/views/posts/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

MercedesBlog/app/views/posts/show.html.erb
<article class="post">
  <section class="post-head mt-2 mb-2">
    <h1 class="card-title"><%= @post.title %></h1>
    <small> <%= @post.created_at.to_date.strftime("%d %B, %Y")%></small>
    |
    <%= link_to 'Change', edit_post_path(@post) %>
    <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'} %>
  </section>

  <section class="post-body mt-3 mb-2 pt-1">
    <p><%= @post.body.html_safe %></p>
  </section>
</article>

<%= render 'disqus' %>